version: "3"

services:
  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: cozymusic-php
    environment:
      MYSQL_HOST: cozymusic-mariadb
      MYSQL_DB: cozymusic
      MYSQL_USER: cozymusic_app
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - "./app:/var/www/html"
    depends_on:
      - mariadb

  nginx:
    image: nginx:alpine
    container_name: cozymusic-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./app:/var/www/html
      - ./config:/etc/nginx/conf.d

  mariadb:
    image: mariadb:11.2.3
    container_name: cozymusic-mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./db:/scripts

volumes:
  mariadbdata:
